### ISSUE TITLE
Include system prompt while calculation prompt token limit 

### ISSUE THREAD

**Issue by sauravpanda** [Cloud-Code-AI/kaizen#271]
We need to pass system prompt, too for calculating the tokens:

file: kaizen/llm/provider.py
```
def is_inside_token_limit(self, PROMPT: str, percentage: float = 0.8) -> bool:
        # TODO: Also include system prompt
```

**Comment by Khaleelhabeeb** [comment]
To include the system prompt in the token calculation in the ' is_inside_token_limit ' method, we can modify the method to concatenate the system prompt with the user prompt. I will open a PR with a probable solution

**Comment by Khaleelhabeeb** [comment]
Thany you so much 
here is my twitter [](https://x.com/khaleel_habib)
