### ISSUE TITLE
Feature Request: Extend `generate_tests` method to support folder paths

### ISSUE THREAD

**Issue by MashyBasker** [Cloud-Code-AI/kaizen#392]
The current `generate_tests` method in the `UnitTestGenerator` class only accepts a single file path. This request proposes extending the method to accept a folder path, allowing it to generate tests for all files within the directory.

*Triage needed*

**Comment by sauravpanda** [comment]
Would love this feature, do you want to add it or I can do it?

**Comment by MashyBasker** [comment]
I'll be happy to work on it

**Comment by sauravpanda** [comment]
Okay, I should be available for the next few hours if you have any doubts!
