### ISSUE TITLE
feat: Add support for local LLMs

### ISSUE THREAD

**Issue by MashyBasker** [Cloud-Code-AI/kaizen#465]
**Current Behavior**:
Kaizen currently supports only cloud-based AI models (e.g., OpenAI, Azure, Groq, etc.).

**Proposed Improvement**:
Extend Kaizen's functionality to support local large language models (LLMs) by integrating providers like Ollama. This would allow users to leverage on-premise or locally-hosted AI models, offering greater flexibility, privacy, and control over their AI deployments.

**Comment by sauravpanda** [comment]
We actually have support for local LLMs, I will try to document how to set it up!

**Comment by MashyBasker** [comment]
That's great! I'll close this issue now.
