### ISSUE TITLE
[feat]: graph visualizer for codebase

### ISSUE THREAD

**Issue by SwapnilChand** [Cloud-Code-AI/kaizen#533]
An overview graph visualization of a codebase can help devs to quick start work in new code bases.

**Comment by ShivanshJ** [comment]
Was wondering if this will feature relationships between functions within classes too, will the class name be shown as a separate node in the graph?

secondly, instead of defining your own graph structure in sqlite, why not use neo4j ?

**Comment by sauravpanda** [comment]
We can for sure highlight nodes differently! @SwapnilChand lets try to do that!

I think we decided against neo4j as its not completely open source, we want to ensure that it is opened source so we don't use things that might need licensing.

**Comment by SwapnilChand** [comment]
Closing this issue
